<?php
/**
 * Front Page Template
 *
 * Layout:
 * 1. Hero with search bar ("Find the right SaaS tool")
 * 2. Trust signals (stats)
 * 3. Featured reviews grid (top-rated)
 * 4. Trending deals
 * 5. Category browsing section
 * 6. Latest blog posts
 * 7. Comparison CTAs
 *
 * @package SaasFinder
 */

get_header();

// Pre-fetch stats
$total_reviews = wp_count_posts('saas-review')->publish;
$total_deals   = wp_count_posts('saas-deal')->publish;
$total_cats    = wp_count_terms(array('taxonomy' => 'saas-category', 'hide_empty' => true));
if (is_wp_error($total_cats)) $total_cats = 0;
?>

<!-- Hero Section -->
<section style="padding:var(--space-16) 0 var(--space-12);background:linear-gradient(180deg, var(--bg-surface) 0%, var(--bg-card) 100%);text-align:center;">
    <div class="container" style="max-width:700px;margin-inline:auto;">
        <h1 style="font-size:clamp(var(--text-3xl),5vw,3.5rem);margin-bottom:var(--space-4);">Find the Right SaaS Tool</h1>
        <p style="font-size:var(--text-lg);color:var(--text-secondary);margin-bottom:var(--space-8);">
            In-depth reviews, honest comparisons, and exclusive deals on B2B and B2C software — tested by hand, not generated by bots.
        </p>
        <form class="search-bar" role="search" action="<?php echo esc_url(home_url('/')); ?>" method="get" style="max-width:500px;margin-inline:auto;">
            <label for="hero-search" class="sr-only">Search SaaS tools</label>
            <input type="search" id="hero-search" class="search-bar__input" name="s" placeholder="Search tools, categories, or questions..." autocomplete="off">
            <button type="submit" class="search-bar__btn">Search</button>
        </form>

        <!-- Trust Stats -->
        <div style="display:flex;justify-content:center;gap:var(--space-8);margin-top:var(--space-8);flex-wrap:wrap;">
            <div>
                <span style="font-size:var(--text-2xl);font-weight:var(--font-bold);color:var(--brand-primary);display:block;"><?php echo esc_html($total_reviews); ?>+</span>
                <span style="font-size:var(--text-sm);color:var(--text-muted);">Tools Reviewed</span>
            </div>
            <div>
                <span style="font-size:var(--text-2xl);font-weight:var(--font-bold);color:var(--brand-primary);display:block;"><?php echo esc_html($total_cats); ?></span>
                <span style="font-size:var(--text-sm);color:var(--text-muted);">Categories</span>
            </div>
            <div>
                <span style="font-size:var(--text-2xl);font-weight:var(--font-bold);color:var(--brand-primary);display:block;"><?php echo esc_html($total_deals); ?></span>
                <span style="font-size:var(--text-sm);color:var(--text-muted);">Active Deals</span>
            </div>
        </div>
    </div>
</section>

<!-- Featured Reviews -->
<section style="padding:var(--space-12) 0;">
    <div class="container">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:var(--space-6);">
            <h2 style="margin:0;">Top-Rated Tools</h2>
            <a href="<?php echo esc_url(get_post_type_archive_link('saas-review')); ?>" style="font-size:var(--text-sm);font-weight:var(--font-medium);">View All →</a>
        </div>
        <div class="grid-auto">
            <?php
            $featured = new WP_Query(array(
                'post_type'      => 'saas-review',
                'posts_per_page' => 6,
                'meta_key'       => '_saas_tool_rating',
                'orderby'        => 'meta_value_num',
                'order'          => 'DESC',
            ));

            while ($featured->have_posts()) : $featured->the_post();
                get_template_part('template-parts/components/review-card');
            endwhile;
            wp_reset_postdata();
            ?>
        </div>
    </div>
</section>

<!-- Trending Deals -->
<?php
$deals = new WP_Query(array(
    'post_type'      => 'saas-deal',
    'posts_per_page' => 3,
    'orderby'        => 'date',
    'order'          => 'DESC',
));
if ($deals->have_posts()) :
?>
<section style="padding:var(--space-12) 0;background:var(--bg-surface);">
    <div class="container">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:var(--space-6);">
            <h2 style="margin:0;">Trending Deals</h2>
            <a href="<?php echo esc_url(get_post_type_archive_link('saas-deal')); ?>" style="font-size:var(--text-sm);font-weight:var(--font-medium);">All Deals →</a>
        </div>
        <div class="grid-auto">
            <?php
            while ($deals->have_posts()) : $deals->the_post();
                get_template_part('template-parts/components/deal-card');
            endwhile;
            wp_reset_postdata();
            ?>
        </div>
    </div>
</section>
<?php endif; ?>

<!-- Browse by Category -->
<section style="padding:var(--space-12) 0;">
    <div class="container">
        <h2 style="margin-top:0;margin-bottom:var(--space-6);">Browse by Category</h2>
        <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:var(--space-3);">
            <?php
            $categories = get_terms(array(
                'taxonomy'   => 'saas-category',
                'hide_empty' => true,
                'number'     => 12,
                'orderby'    => 'count',
                'order'      => 'DESC',
            ));

            if (!is_wp_error($categories)) :
                foreach ($categories as $cat) :
            ?>
                <a href="<?php echo esc_url(home_url('/best/' . $cat->slug . '-software/')); ?>" style="display:block;padding:var(--space-4);border:1px solid var(--border-default);border-radius:var(--border-radius);text-decoration:none;color:var(--text-primary);transition:all var(--transition-fast);" onmouseover="this.style.borderColor='var(--brand-primary)'" onmouseout="this.style.borderColor='var(--border-default)'">
                    <strong style="display:block;"><?php echo esc_html($cat->name); ?></strong>
                    <span style="font-size:var(--text-sm);color:var(--text-muted);"><?php echo esc_html($cat->count); ?> tools reviewed</span>
                </a>
            <?php
                endforeach;
            endif;
            ?>
        </div>
    </div>
</section>

<!-- Popular Comparisons -->
<section style="padding:var(--space-12) 0;background:var(--bg-surface);">
    <div class="container">
        <h2 style="margin-top:0;margin-bottom:var(--space-6);">Popular Comparisons</h2>
        <div style="display:flex;flex-wrap:wrap;gap:var(--space-2);">
            <?php
            // Auto-generate comparison links from top-rated tools in same categories
            $top_tools = get_posts(array(
                'post_type'      => 'saas-review',
                'posts_per_page' => 8,
                'meta_key'       => '_saas_tool_rating',
                'orderby'        => 'meta_value_num',
                'order'          => 'DESC',
            ));

            // Create comparison pairs from adjacent top tools
            for ($i = 0; $i < count($top_tools) - 1; $i += 2) :
                $slug1 = $top_tools[$i]->post_name;
                $slug2 = $top_tools[$i + 1]->post_name;
                $name1 = get_the_title($top_tools[$i]->ID);
                $name2 = get_the_title($top_tools[$i + 1]->ID);
            ?>
                <a href="<?php echo esc_url(home_url('/compare/' . $slug1 . '-vs-' . $slug2 . '/')); ?>" class="content-cluster__link">
                    <?php echo esc_html($name1); ?> vs <?php echo esc_html($name2); ?>
                </a>
            <?php endfor; ?>
        </div>
    </div>
</section>

<!-- Latest Blog Posts -->
<?php
$blog = new WP_Query(array(
    'post_type'      => 'post',
    'posts_per_page' => 4,
));
if ($blog->have_posts()) :
?>
<section style="padding:var(--space-12) 0;">
    <div class="container">
        <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:var(--space-6);">
            <h2 style="margin:0;">Latest from the Blog</h2>
            <a href="<?php echo esc_url(get_permalink(get_option('page_for_posts'))); ?>" style="font-size:var(--text-sm);font-weight:var(--font-medium);">All Posts →</a>
        </div>
        <div class="grid-auto">
            <?php
            while ($blog->have_posts()) : $blog->the_post();
                get_template_part('template-parts/components/blog-card');
            endwhile;
            wp_reset_postdata();
            ?>
        </div>
    </div>
</section>
<?php endif; ?>

<?php get_footer(); ?>
